-- H2 测试库建表脚本（MySQL 兼容模式），与生产 Flyway 结构保持一致

DROP TABLE IF EXISTS TAB_GOODS;
CREATE TABLE TAB_GOODS (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_CODE          VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME          VARCHAR(200)  NOT NULL DEFAULT '',
    S_CATEGORY      VARCHAR(100)  NOT NULL DEFAULT '',
    S_SPEC          VARCHAR(200)  NOT NULL DEFAULT '',
    S_BASE_UNIT     VARCHAR(50)   NOT NULL DEFAULT '',
    I_STATUS        TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_GOODS_UNIT;
CREATE TABLE TAB_GOODS_UNIT (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    S_UNIT_NAME     VARCHAR(50)   NOT NULL DEFAULT '',
    I_CONVERT_RATE  INT           NOT NULL DEFAULT 1,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_WAREHOUSE;
CREATE TABLE TAB_WAREHOUSE (
    S_ID             VARCHAR(50)   NOT NULL DEFAULT '',
    S_CODE           VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME           VARCHAR(200)  NOT NULL DEFAULT '',
    I_LOCATION_TYPE  TINYINT       NOT NULL DEFAULT 1,
    I_STATUS         TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER    VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER    VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_CUSTOMER;
CREATE TABLE TAB_CUSTOMER (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME          VARCHAR(200)  NOT NULL DEFAULT '',
    S_CONTACT       VARCHAR(100)  NOT NULL DEFAULT '',
    S_ADDRESS       VARCHAR(500)  NOT NULL DEFAULT '',
    S_PHONE         VARCHAR(50)   NOT NULL DEFAULT '',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_SUPPLIER;
CREATE TABLE TAB_SUPPLIER (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME          VARCHAR(200)  NOT NULL DEFAULT '',
    S_CONTACT       VARCHAR(100)  NOT NULL DEFAULT '',
    S_PHONE         VARCHAR(50)   NOT NULL DEFAULT '',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_STOCK;
CREATE TABLE TAB_STOCK (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    S_WAREHOUSE_ID  VARCHAR(50)   NOT NULL DEFAULT '',
    I_QTY           INT           NOT NULL DEFAULT 0,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID),
    CONSTRAINT IDX_TAB_STOCK_GOODS_WH UNIQUE (S_GOODS_ID, S_WAREHOUSE_ID)
);

DROP TABLE IF EXISTS TAB_STOCK_FLOW;
CREATE TABLE TAB_STOCK_FLOW (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    S_WAREHOUSE_ID  VARCHAR(50)   NOT NULL DEFAULT '',
    I_FLOW_TYPE     TINYINT       NOT NULL DEFAULT 0,
    I_CHANGE_QTY    INT           NOT NULL DEFAULT 0,
    S_SOURCE_NO     VARCHAR(50)   NOT NULL DEFAULT '',
    S_REMARK        VARCHAR(500)  NOT NULL DEFAULT '',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_PURCHASE;
CREATE TABLE TAB_PURCHASE (
    S_ID              VARCHAR(50)   NOT NULL DEFAULT '',
    S_PURCHASE_NO     VARCHAR(50)   NOT NULL DEFAULT '',
    S_SUPPLIER_ID     VARCHAR(50)   NOT NULL DEFAULT '',
    S_WAREHOUSE_ID    VARCHAR(50)   NOT NULL DEFAULT '',
    I_TOTAL_AMOUNT    INT           NOT NULL DEFAULT 0,
    DT_PURCHASE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_CREATE_TIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER     VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER     VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_PURCHASE_ITEM;
CREATE TABLE TAB_PURCHASE_ITEM (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_PURCHASE_ID   VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    I_QTY_BASE      INT           NOT NULL DEFAULT 0,
    S_INPUT_UNIT    VARCHAR(50)   NOT NULL DEFAULT '',
    I_INPUT_QTY     INT           NOT NULL DEFAULT 0,
    I_PRICE         INT           NOT NULL DEFAULT 0,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_SALE_ORDER;
CREATE TABLE TAB_SALE_ORDER (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_SALE_NO       VARCHAR(50)   NOT NULL DEFAULT '',
    I_SALE_TYPE     TINYINT       NOT NULL DEFAULT 1,
    S_CUSTOMER_ID   VARCHAR(50)   NOT NULL DEFAULT '',
    S_WAREHOUSE_ID  VARCHAR(50)   NOT NULL DEFAULT '',
    I_STATUS        TINYINT       NOT NULL DEFAULT 1,
    I_TOTAL_AMOUNT  INT           NOT NULL DEFAULT 0,
    DT_SHIP_TIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_SALE_ORDER_ITEM;
CREATE TABLE TAB_SALE_ORDER_ITEM (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_SALE_ID       VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    I_QTY_BASE      INT           NOT NULL DEFAULT 0,
    S_INPUT_UNIT    VARCHAR(50)   NOT NULL DEFAULT '',
    I_INPUT_QTY     INT           NOT NULL DEFAULT 0,
    I_PRICE         INT           NOT NULL DEFAULT 0,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

-- ============================================================
-- 第二期财务模块表（H2 测试）
-- ============================================================

DROP TABLE IF EXISTS TAB_RECEIVABLE;
CREATE TABLE TAB_RECEIVABLE (
    S_ID               VARCHAR(50)   NOT NULL DEFAULT '',
    S_SALE_ID          VARCHAR(50)   NOT NULL DEFAULT '',
    S_CUSTOMER_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    I_TOTAL_AMOUNT     INT           NOT NULL DEFAULT 0,
    I_RECEIVED_AMOUNT  INT           NOT NULL DEFAULT 0,
    I_STATUS           TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER      VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER      VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_PAYABLE;
CREATE TABLE TAB_PAYABLE (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_PURCHASE_ID   VARCHAR(50)   NOT NULL DEFAULT '',
    S_SUPPLIER_ID   VARCHAR(50)   NOT NULL DEFAULT '',
    I_TOTAL_AMOUNT  INT           NOT NULL DEFAULT 0,
    I_PAID_AMOUNT   INT           NOT NULL DEFAULT 0,
    I_STATUS        TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_FUND_FLOW;
CREATE TABLE TAB_FUND_FLOW (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    I_FLOW_TYPE     TINYINT       NOT NULL DEFAULT 0,
    I_DIRECTION     TINYINT       NOT NULL DEFAULT 0,
    I_AMOUNT        INT           NOT NULL DEFAULT 0,
    S_PARTY_ID      VARCHAR(50)   NOT NULL DEFAULT '',
    S_SOURCE_NO     VARCHAR(50)   NOT NULL DEFAULT '',
    S_CATEGORY_ID   VARCHAR(50)   NOT NULL DEFAULT '',
    D_OCCUR_DATE    DATE          NOT NULL DEFAULT '1970-01-01',
    S_REMARK        VARCHAR(500)  NOT NULL DEFAULT '',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_EXPENSE_CATEGORY;
CREATE TABLE TAB_EXPENSE_CATEGORY (
    S_ID             VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME           VARCHAR(100)  NOT NULL DEFAULT '',
    I_CATEGORY_TYPE  TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER    VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER    VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

-- 第一期销售单表增加期望送达日期字段
ALTER TABLE TAB_SALE_ORDER ADD COLUMN D_EXPECT_DELIVERY DATE NOT NULL DEFAULT '1970-01-01';

-- ============================================================
-- 多租户改造（H2 测试）
-- ============================================================

DROP TABLE IF EXISTS TAB_TENANT;
CREATE TABLE TAB_TENANT (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_NAME          VARCHAR(200)  NOT NULL DEFAULT '',
    I_STATUS        TINYINT       NOT NULL DEFAULT 1,
    DT_OPEN_TIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS TAB_ACCOUNT;
CREATE TABLE TAB_ACCOUNT (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_LOGIN_NAME    VARCHAR(100)  NOT NULL DEFAULT '',
    S_PASSWORD      VARCHAR(200)  NOT NULL DEFAULT '',
    S_TENANT_ID     VARCHAR(50)   NOT NULL DEFAULT '',
    I_ROLE          TINYINT       NOT NULL DEFAULT 2,
    I_STATUS        TINYINT       NOT NULL DEFAULT 1,
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

-- 业务表增加租户字段（H2）
ALTER TABLE TAB_GOODS             ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_GOODS_UNIT        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_WAREHOUSE         ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_CUSTOMER          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_SUPPLIER          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_STOCK             ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_STOCK_FLOW        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_PURCHASE          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_PURCHASE_ITEM     ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_SALE_ORDER        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_SALE_ORDER_ITEM   ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_RECEIVABLE        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_PAYABLE           ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_FUND_FLOW         ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE TAB_EXPENSE_CATEGORY  ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '';

-- 租户到期日期（V4）
ALTER TABLE TAB_TENANT ADD COLUMN D_EXPIRE_DATE DATE NOT NULL DEFAULT '2099-12-31';

-- ============================================================
-- AI 智能问数（H2 测试，V5）
-- ============================================================

-- 租户增加 AI 开关
ALTER TABLE TAB_TENANT ADD COLUMN I_AI_ENABLED TINYINT NOT NULL DEFAULT 0;

-- AI 问答日志表
DROP TABLE IF EXISTS TAB_AI_CHAT_LOG;
CREATE TABLE TAB_AI_CHAT_LOG (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_QUESTION      VARCHAR(1000) NOT NULL DEFAULT '',
    S_INTENT        VARCHAR(50)   NOT NULL DEFAULT '',
    I_SUCCESS       TINYINT       NOT NULL DEFAULT 0,
    I_DEGRADED      TINYINT       NOT NULL DEFAULT 0,
    S_TENANT_ID     VARCHAR(50)   NOT NULL DEFAULT '',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

-- ============================================================
-- 产品模板（V6, 平台级）
-- ============================================================

DROP TABLE IF EXISTS TAB_GOODS_TEMPLATE;
CREATE TABLE TAB_GOODS_TEMPLATE (
    S_ID         VARCHAR(50)   NOT NULL DEFAULT '',
    S_CODE       VARCHAR(50)   NOT NULL DEFAULT '',
    S_CATEGORY   VARCHAR(100)  NOT NULL DEFAULT '',
    S_NAME       VARCHAR(200)  NOT NULL DEFAULT '',
    S_SPEC       VARCHAR(200)  NOT NULL DEFAULT '',
    S_BASE_UNIT  VARCHAR(50)   NOT NULL DEFAULT '',
    PRIMARY KEY (S_ID)
);

-- 插入几条模板用于测试产品初始化
INSERT INTO TAB_GOODS_TEMPLATE (S_ID, S_CODE, S_CATEGORY, S_NAME, S_SPEC, S_BASE_UNIT) VALUES
('T001', '010101', '连卷袋', '连卷袋', '25*35', '公斤'),
('T002', '010102', '连卷袋', '连卷袋', '30*40', '公斤'),
('T003', '020101', '保鲜膜与胶带', '保鲜膜 大卷', '45cm*400m', '卷');

-- 产品包装单位模板（V7, 平台级）
DROP TABLE IF EXISTS TAB_GOODS_UNIT_TEMPLATE;
CREATE TABLE TAB_GOODS_UNIT_TEMPLATE (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT '',
    S_GOODS_CODE    VARCHAR(50)   NOT NULL DEFAULT '',
    S_UNIT_NAME     VARCHAR(50)   NOT NULL DEFAULT '',
    I_CONVERT_RATE  INT           NOT NULL DEFAULT 1,
    PRIMARY KEY (S_ID)
);

-- 测试用：给连卷袋25*35加一个箱=25公斤
INSERT INTO TAB_GOODS_UNIT_TEMPLATE (S_ID, S_GOODS_CODE, S_UNIT_NAME, I_CONVERT_RATE) VALUES
('U001', '010101', '箱', 25);
