-- 产品-超市耗材供应商系统-多租户改造建表脚本
-- 无存量数据，直接加字段与改索引；平台管理员账号由应用启动初始化器创建（BCrypt 密文）

-- ============================================================
-- 租户（商家）表
-- ============================================================
CREATE TABLE TAB_TENANT (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT ''  COMMENT '主键',
    S_NAME          VARCHAR(200)  NOT NULL DEFAULT ''  COMMENT '商家名称',
    I_STATUS        TINYINT       NOT NULL DEFAULT 1   COMMENT '状态：1启用 2停用',
    DT_OPEN_TIME    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开通时间',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT ''  COMMENT '创建人',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT ''  COMMENT '更新人',
    PRIMARY KEY (S_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台-租户-商家表';

-- ============================================================
-- 账号表（支持一租户多账号 + 角色）
-- ============================================================
CREATE TABLE TAB_ACCOUNT (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT ''  COMMENT '主键',
    S_LOGIN_NAME    VARCHAR(100)  NOT NULL DEFAULT ''  COMMENT '登录名（全局唯一）',
    S_PASSWORD      VARCHAR(200)  NOT NULL DEFAULT ''  COMMENT '密码（BCrypt 密文）',
    S_TENANT_ID     VARCHAR(50)   NOT NULL DEFAULT ''  COMMENT '所属租户ID（平台管理员为空）',
    I_ROLE          TINYINT       NOT NULL DEFAULT 2   COMMENT '角色：1平台管理员 2商家管理员（预留3业务员等）',
    I_STATUS        TINYINT       NOT NULL DEFAULT 1   COMMENT '状态：1启用 2停用',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT ''  COMMENT '创建人',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT ''  COMMENT '更新人',
    PRIMARY KEY (S_ID),
    UNIQUE KEY IDX_TAB_ACCOUNT_LOGIN (S_LOGIN_NAME),
    KEY IDX_TAB_ACCOUNT_TENANT (S_TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平台-租户-账号表';

-- ============================================================
-- 业务表增加租户字段 S_TENANT_ID 与索引
-- ============================================================
ALTER TABLE TAB_GOODS             ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_GOODS_UNIT        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_WAREHOUSE         ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_CUSTOMER          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_SUPPLIER          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_STOCK             ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_STOCK_FLOW        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_PURCHASE          ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_PURCHASE_ITEM     ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_SALE_ORDER        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_SALE_ORDER_ITEM   ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_RECEIVABLE        ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_PAYABLE           ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_FUND_FLOW         ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';
ALTER TABLE TAB_EXPENSE_CATEGORY  ADD COLUMN S_TENANT_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '租户ID';

CREATE INDEX IDX_TAB_GOODS_TENANT            ON TAB_GOODS (S_TENANT_ID);
CREATE INDEX IDX_TAB_GOODS_UNIT_TENANT       ON TAB_GOODS_UNIT (S_TENANT_ID);
CREATE INDEX IDX_TAB_WAREHOUSE_TENANT        ON TAB_WAREHOUSE (S_TENANT_ID);
CREATE INDEX IDX_TAB_CUSTOMER_TENANT         ON TAB_CUSTOMER (S_TENANT_ID);
CREATE INDEX IDX_TAB_SUPPLIER_TENANT         ON TAB_SUPPLIER (S_TENANT_ID);
CREATE INDEX IDX_TAB_STOCK_TENANT            ON TAB_STOCK (S_TENANT_ID);
CREATE INDEX IDX_TAB_STOCK_FLOW_TENANT       ON TAB_STOCK_FLOW (S_TENANT_ID);
CREATE INDEX IDX_TAB_PURCHASE_TENANT         ON TAB_PURCHASE (S_TENANT_ID);
CREATE INDEX IDX_TAB_PURCHASE_ITEM_TENANT    ON TAB_PURCHASE_ITEM (S_TENANT_ID);
CREATE INDEX IDX_TAB_SALE_ORDER_TENANT       ON TAB_SALE_ORDER (S_TENANT_ID);
CREATE INDEX IDX_TAB_SALE_ORDER_ITEM_TENANT  ON TAB_SALE_ORDER_ITEM (S_TENANT_ID);
CREATE INDEX IDX_TAB_RECEIVABLE_TENANT       ON TAB_RECEIVABLE (S_TENANT_ID);
CREATE INDEX IDX_TAB_PAYABLE_TENANT          ON TAB_PAYABLE (S_TENANT_ID);
CREATE INDEX IDX_TAB_FUND_FLOW_TENANT        ON TAB_FUND_FLOW (S_TENANT_ID);
CREATE INDEX IDX_TAB_EXPENSE_CATEGORY_TENANT ON TAB_EXPENSE_CATEGORY (S_TENANT_ID);

-- ============================================================
-- 唯一性调整：全局唯一 -> 租户内唯一（组合唯一索引）
-- ============================================================
DROP INDEX IDX_TAB_GOODS_S_CODE ON TAB_GOODS;
CREATE UNIQUE INDEX IDX_TAB_GOODS_TENANT_CODE ON TAB_GOODS (S_TENANT_ID, S_CODE);

DROP INDEX IDX_TAB_WAREHOUSE_S_CODE ON TAB_WAREHOUSE;
CREATE UNIQUE INDEX IDX_TAB_WAREHOUSE_TENANT_CODE ON TAB_WAREHOUSE (S_TENANT_ID, S_CODE);

DROP INDEX IDX_TAB_PURCHASE_S_PURCHASE_NO ON TAB_PURCHASE;
CREATE UNIQUE INDEX IDX_TAB_PURCHASE_TENANT_NO ON TAB_PURCHASE (S_TENANT_ID, S_PURCHASE_NO);

DROP INDEX IDX_TAB_SALE_ORDER_S_SALE_NO ON TAB_SALE_ORDER;
CREATE UNIQUE INDEX IDX_TAB_SALE_ORDER_TENANT_NO ON TAB_SALE_ORDER (S_TENANT_ID, S_SALE_NO);
