-- AI 智能问数：租户增加 AI 开关 + 可选问答日志表

-- 租户增加 AI 开关字段（默认关闭，由平台管理员开通作为增值服务）
ALTER TABLE TAB_TENANT ADD COLUMN I_AI_ENABLED TINYINT NOT NULL DEFAULT 0 COMMENT 'AI开关：0关闭 1开启';

-- AI 问答日志表（业务表，随租户隔离；是否落库由配置 consumables.ai.log-enabled 控制）
CREATE TABLE TAB_AI_CHAT_LOG (
    S_ID            VARCHAR(50)   NOT NULL DEFAULT ' ' COMMENT '主键',
    S_QUESTION      VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '用户问题',
    S_INTENT        VARCHAR(50)   NOT NULL DEFAULT '' COMMENT '识别到的意图编码（拒答为空）',
    I_SUCCESS       TINYINT       NOT NULL DEFAULT 0 COMMENT '是否成功回答：0否 1是',
    I_DEGRADED      TINYINT       NOT NULL DEFAULT 0 COMMENT '是否降级：0否 1是',
    S_TENANT_ID     VARCHAR(50)   NOT NULL DEFAULT '' COMMENT '所属租户ID',
    DT_CREATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    DT_UPDATE_TIME  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    S_CREATE_USER   VARCHAR(100)  NOT NULL DEFAULT '' COMMENT '创建人',
    S_UPDATE_USER   VARCHAR(100)  NOT NULL DEFAULT '' COMMENT '更新人',
    PRIMARY KEY (S_ID),
    KEY IDX_TAB_AI_CHAT_LOG_TENANT (S_TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='耗材平台-AI-问答日志';
