-- 销售单明细增加折扣、折后价、备注字段

ALTER TABLE TAB_SALE_ORDER_ITEM ADD COLUMN I_DISCOUNT INT NOT NULL DEFAULT 100 COMMENT '折扣百分比（100=不打折，90=九折）';
ALTER TABLE TAB_SALE_ORDER_ITEM ADD COLUMN I_DISCOUNT_PRICE INT NOT NULL DEFAULT 0 COMMENT '折后单价（分）';
ALTER TABLE TAB_SALE_ORDER_ITEM ADD COLUMN S_REMARK VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注';
