-- 销售单增加物流信息字段（快递公司、快递单号、物流状态）

ALTER TABLE TAB_SALE_ORDER ADD COLUMN I_DELIVER_STATUS INT NOT NULL DEFAULT 1 COMMENT '物流状态：1未发货 2已发货';
ALTER TABLE TAB_SALE_ORDER ADD COLUMN S_EXPRESS_COMPANY VARCHAR(100) NOT NULL DEFAULT '' COMMENT '快递公司';
ALTER TABLE TAB_SALE_ORDER ADD COLUMN S_EXPRESS_NO VARCHAR(100) NOT NULL DEFAULT '' COMMENT '快递/物流单号';
